### ISSUE TITLE
Create a utility that extracts the licenses based on a code repo URL

### ISSUE THREAD

**Issue by npch** [softwaresaved/habeas-corpus#10]
Should be able to get license just from the GitHub API

**Comment by ha0ye** [comment]
I can handle this, from past experience interfacing with the github api in R.

**Comment by ha0ye** [comment]
Basic functionality is set now, and the output data is updated.

There are some minor squiggles to resolve, e.g. in one case, the organization github was linked, and not a specific repo.

**Comment by sdruskat** [comment]
Great, I think in order to close this issue, we should just merge the license info back into a version of the dataset file, e.g., based on [`CORD19_software_popularity_sampled_QA_DOI.csv`](https://github.com/softwaresaved/habeas-corpus/blob/main/data/output/CORD19_software_popularity_sampled_QA_DOI.csv)?

**Comment by ha0ye** [comment]
@sdruskat I'll make a new PR to run the new file through my script.
